### ISSUE TITLE
[JOSS review] Input checks

### ISSUE THREAD

**Issue by jakobbossek** [easystats/see#175]
Unfortunately there are almost no sanity checks 😢  Passing inappropriate parameters hence may lead to error messages that are hard to understand.  Please use, e.g. [checkmate](https://github.com/mllg/checkmate) for fast and versatile argument checks.

**Comment by IndrajeetPatil** [comment]
Hi, can you please give an example of what do you mean by there not being any sanity checks?

**Comment by jakobbossek** [comment]
Sure.

```r
ggplot(iris, aes(x = Species, y = Sepal.Length, fill = Species)) +  geom_violindot(scale = "arae")
```
throws the following error. The problem is a typo (arae vs. area), but the scale parameter is not checked for appropriate values. Hence, I get the following confusing error which does not give any hint what is actually wrong.
```
Fehler in `$<-.data.frame`(`*tmp*`, "xmaxv", value = numeric(0)) :
  Ersetzung hat 0 Zeilen, Daten haben 512
```

You can easily avoid this by adding the following to `geom_violindot`:
```r
checkmate::assert_choice(scale, choices = c("area", "some_other_valid_argument_value"))
```

**Comment by jakobbossek** [comment]
Actually, this is not fixed at all. The `scale` parameter was just an example. This commit did not change much.
Examples: in `coord_radar` the `start` parameter is not checked. 
```r
if (require("dplyr") && require("tidyr") && require("ggplot2")) {
  data <- iris %>%
    group_by(Species) %>%
    summarise_all(mean) %>%
    pivot_longer(-Species)

  data %>%
    ggplot(aes(x = name, y = value, color = Species, group = Species)) +
    geom_polygon(fill = NA, size = 2) +
    coord_radar(start = "abc")
}
```

```
Error in x + coord$start :
  non numeric argument for binary operator
```

In `plot.see_easycorrelation I can pass negative values for `size_point`. This does not break the code, but it actually makes no sense. 

There are many more examples.

**Comment by IndrajeetPatil** [comment]
I am not sure if it makes sense to check nonsensical inputs to arguments because it is highly unlikely that anyone is actually going to make that mistake in the wild.

For example, `ggplot2` is used by millions of users and yet there is no check for `size` not being negative and for a good reason: it is highly unlikely that anyone is actually going to enter negative values in this context.

``` r
library(ggplot2)

ggplot(mtcars, aes(wt, mpg)) + 
  geom_point(size = -2)
```

![](https://i.imgur.com/L5395l5.png)

<sup>Created on 2021-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

At least, that's my take on this issue. I will let other authors comment on this, and will keep the issue open for the same.

**Comment by jakobbossek** [comment]
Sorry for being nitpicky, but this is what bothers me about the majority of R packages. Of course it is unlikely that some user calls, say `coord_radar` by passing a character (vector) for the `start` parameter. However, if the plot code is embedded in a loop or some larger script  and the author messed up something by passing down the wrong variable, a meaningful error message would help a lot to identify the issue quickly.

I really suggest to adopt something like [checkmate](https://github.com/mllg/checkmate). It is easy to use and very fast (see the [R Journal paper](https://journal.r-project.org/archive/2017/RJ-2017-028/index.html) for a benchmark). Alternatively just use `stopifnot`. E.g. for the `start` parameter it could be something like:
```r
stopifnot(is.numeric(start), (length(start) == 1))
```

**Comment by bwiernik** [comment]
(I would really appreciate if you would use "input checks" rather than "sanity checks" as a term.)

**Comment by bwiernik** [comment]
A few general thoughts:

1. We try to limit the number of dependencies in packages to the absolute minimum, so using checkmate isn't an option. Any checks would be implemented with tryCatch() or stopifnot()

2. For the geom_ and theme_ functions, these are really minor extensions to the broader ggplot2 framework. As a result, it is critical that these have consistent behavior with the underlying ggplot2 framework. Although a negative size value might not make much sense conceptually, allowing that is the behavior of every ggplot2 geom and aesthetic. It's not uncommon, for example, for users to use negative size values as a method to suppress rendering of some elements using negative size values. To prevent that would potentially produce jarring inconsistency with the behavior of other geoms. 

   I encountered a similar issue recently with another ggplot2 extension. This package defined an unusual behavior for position_dodge(), which meant that its geoms did not align with base ggplot2 geoms when dodged. The package developer did this to ensure the new geoms never overflowed the plot area, but it made the package incompatible with the underlying ggplot2 framework. They needed to adjust the behavior so that dodge yielded consistent behavior and to create a new position yielded the previous "safer" behavior. 

3. For input that actually yield errors, such as passing a character value to a coord_ `start` argument, compatibility is less of a concern. But I also think you are overstating the size of the concern. As stated above, the geom_, coord_, and theme_ functions in this package are minor extensions to underlying ggplot2 functions. A user that would encounter a problem with coord_radar() would encounter exactly the same issue with ggplot2::coord_polar(); a user that would encounter an issue with geom_point_borderless() would encounter exactly the same issue with ggplot2::geom_point(), etc. Adding type checks for these small ggplot2 functions (which I suspect will mostly be used internally by the model plotting functions that are the heart of this package) will not meaningfully affect user experience because they aren't present in any of the core ggplot2 functions. From my perspective, this would be an issue that would appropriately be fixed in ggplot2 itself at the stage of rendering a ggplot, not individually in every geom_, coord_, stat_, etc. call. 

   Two additional comments here. One, importantly, evaluation of data in ggplot is not done until plot _rebdering_, not plot construction. In many common cases, such as a user passing arguments with `vars()` or an external vector, it's not possible to determine if input is valid because these arguments are passed lazily to ggproto().

   Two, as @IndrajeetPatil alluded to, ggplot2 is a very mature framework and has been in development for over 10 years. I think that if type mismatch issues like this were a major problem for users, it would have presented itself in that time. As it stands, I am very leery of implementing checks that go beyond recommended practices for writing ggplot2 extensions, especially if such checks would (1) be limited to a narrow range of allowable inputs (only bare objects, not names like `foo` or a `vars()` call), (2) would require potentially fragile checks to discern the check-able inputs from allowable-but-uncheckable inputs, and (3) might have negative performance consequences if we short-circuit the typical ggplot2 lazy evaluation workflow.

**Comment by jakobbossek** [comment]
Ok. Even though I am not fully convinced I accept your explanation.
