### ISSUE TITLE
[JOSS review] Improve documentation

### ISSUE THREAD

**Issue by jakobbossek** [easystats/see#178]
The function documentation should be improved:

* Add links to referenced functions from other packages, e.g.instead of `\code{performance::check_homogeneity()}` write `\code{\link[performance]{performance::check_homogeneity}}`.
* Avoid plain URLs. Use links instead. E.g. in the description of `scale_color_material` replace `material design colors (https://www.materialui.co/color)` with `\href{https://www.materialui.co/color}{material design colors}`.
* Describe the expected data types. This is done sometimes, but not mostly not. E.g. in the roxygen2 docs for `plot.see_check_outliers` the expected type for `rescale_distance` is described (logical), but the type for `size_text` is missing (positive numeric). This is linked to #175 and would certainly improve user experience.
* Some parameter descriptions are not satisfactory. E.g. for `coord_radar` the parameter `theta` is described as follows: "Can be 'x' or 'y'." OK, but what does the parameter actually do?

**Comment by IndrajeetPatil** [comment]
Thanks

Creating a checklist for us:

- [ ]  Add links to referenced functions from other packages, e.g.instead of `\code{performance::check_homogeneity()}` write `\code{\link[performance]{performance::check_homogeneity}}`.
- [ ] Avoid plain URLs. Use links instead. E.g. in the description of `scale_color_material` replace `material design colors (https://www.materialui.co/color)` with `\href{https://www.materialui.co/color}{material design colors}`.
- [ ] Describe the expected data types. This is done sometimes, but not mostly not. E.g. in the roxygen2 docs for `plot.see_check_outliers` the expected type for `rescale_distance` is described (logical), but the type for `size_text` is missing (positive numeric). This is linked to #175 and would certainly improve user experience.
- [ ] Some parameter descriptions are not satisfactory. E.g. for `coord_radar` the parameter `theta` is described as follows: "Can be 'x' or 'y'." OK, but what does the parameter actually do?

**Comment by IndrajeetPatil** [comment]
All of your concerns have now been addressed, except:
> Add links to referenced functions from other packages

We prefer not to do this because the `pkgdown` website for our package already does this. 

We are not the only ones to adopt this practice. For example, if you look at `dplyr::select` roxygen [docs](https://github.com/tidyverse/dplyr/blob/ca55fce9226ce9e79f496a3e6634381311f05f47/R/select.R#L47-L49), they are not linking to external packages:

<img width="1258" alt="Screenshot 2021-07-22 at 15 18 17" src="https://user-images.githubusercontent.com/11330453/126645903-f916bb72-1d4f-4e94-a741-67dd19752447.png">

But the `pkgdown` webpage for this function [links](https://dplyr.tidyverse.org/reference/select.html#examples) it successfully:

<img width="1338" alt="Screenshot 2021-07-22 at 15 19 12" src="https://user-images.githubusercontent.com/11330453/126645971-b4fb7a70-9a81-408b-a59d-4c86c1e4c40a.png">

So, it is unnecessary to replace every instance of `\code{performance::check_homogeneity()}` with `\code{\link[performance]{performance::check_homogeneity}}`.
