### ISSUE TITLE
geom_point2 and shapes

### ISSUE THREAD

**Issue by krz** [easystats/see#26]
Hi,
thanks for the package, I especially like the color layout and plot themes.
However, I ran into problems using `geom_point2`

When I run this code

```

library(ggplot2)
library(see)

p1 <- ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length, color = Species)) + 
  geom_point() + theme_modern()

p2 <- ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length, color = Species)) + 
  geom_point2() + theme_modern()

p3 <- ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length, color = Species, shape = Species)) + 
  geom_point() + theme_modern()

p4 <- ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length, color = Species, shape = Species)) + 
  geom_point2() + theme_modern()


plots(p1, p2, p3, p4, ncol = 2, tags = T)
```

it produces the following plot

![Rplot](https://user-images.githubusercontent.com/210623/58434174-a579b500-80ba-11e9-9ac7-6447f71872cb.png)

You can see that plot B produces more diamond like points, compared with A.
Also, geom_point2 seems to not support shapes (plot D). Regulard geom_point works fine (plot C).
```

> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_Germany.1252  LC_CTYPE=English_Germany.1252    LC_MONETARY=English_Germany.1252 LC_NUMERIC=C                     LC_TIME=English_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] see_0.1.0     ggplot2_3.1.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       rstudioapi_0.10  magrittr_1.5     tidyselect_0.2.5 insight_0.3.0    munsell_0.5.0    colorspace_1.4-1 R6_2.4.0         rlang_0.3.4      plyr_1.8.4       dplyr_0.8.1     
[12] tools_3.5.2      grid_3.5.2       gtable_0.3.0     withr_2.1.2      digest_0.6.19    lazyeval_0.2.2   assertthat_0.2.1 tibble_2.1.1     crayon_1.3.4     gridExtra_2.3    purrr_0.3.2     
[23] ggridges_0.5.1   glue_1.3.1       labeling_0.3     compiler_3.5.2   pillar_1.4.0     scales_1.0.0     pkgconfig_2.0.2
```

**Comment by DominiqueMakowski** [comment]
@krz Thanks for reaching out!

1) The diamond-like shapes that we see in plot B are likely due to the size, if you increase the point size or if you save the image with a higher dpi, it should be round.

![image](https://user-images.githubusercontent.com/8875533/58446494-7e12fe80-8133-11e9-947c-9cd10f88e659.png)


2) Somewhat related to the previous point, as you can see in the [very tiny code for these points](https://github.com/easystats/see/blob/master/R/geom_point2.R#L25), it is a wrapper over the classical `geom_point` that specifies `shape = 16` (instead of 1 by default), which is often looking better, especially with a fill colour. However, the fact that the shape is hardcoded prevents its use as an aesthetic. In other words, you cannot use varying shapes as an aesthetic for `geom_point2` as the latter involves one specific shape (the 16th).

Hope it clarifies ☺️
