### ISSUE TITLE
Structural equation models loadings' arrows directions is in the opposite direction

### ISSUE THREAD

**Issue by jorgesinval** [easystats/see#95]
The direction of the arrows from the latent factor to the manifest variables should be the opposite. It is the latent factor that manifests itself in the indicators:

![image](https://user-images.githubusercontent.com/8278071/111136489-b5a3a280-8575-11eb-87a3-268ddbe75ab8.png)

Following the usual standard representation within the SEM framework diagrams, the manifest variables should be represented by rectangles or squares.

**Comment by strengejacke** [comment]
@DominiqueMakowski I think you implemented this plot-method.

**Comment by strengejacke** [comment]
@DominiqueMakowski Is this an easy / quick fix? I would like to submit _see_ the next days... Or should we wait until the next update?

**Comment by DominiqueMakowski** [comment]
Let me take a look now

**Comment by DominiqueMakowski** [comment]
``` r
library(parameters)
library(see)

structure <- "
    # latent variable definitions
      ind60 =~ x1 + x2 + x3
      dem60 =~ y1 + y2 + y3 + y4
      dem65 =~ y5 + y6 + y7 + y8
    # regressions
      dem60 ~ ind60
      dem65 ~ ind60 + dem60
    # residual correlations
      y1 ~~ y5
      y2 ~~ y4 + y6
      y3 ~~ y7
      y4 ~~ y8
      y6 ~~ y8
  "

model <- lavaan::sem(structure, data = lavaan::PoliticalDemocracy)
x <- parameters::model_parameters(model)

plot(x, layout = "fr")
```

![](https://i.imgur.com/zOG8Oye.png)

<sup>Created on 2021-04-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jorgesinval** [comment]
Good! However, manifest variables continue to be drawn with circles. The path from `dem60` to `dem65` is not visible.

**Comment by DominiqueMakowski** [comment]
> Following the usual standard representation within the SEM framework diagrams, the manifest variables should be represented by rectangles or squares.

Ah yes I missed that. Unfortunately, I don't think it's possible in `ggraph` in which I don't see an option for square nodes (https://ggraph.data-imaginist.com/articles/Nodes.html#the-different-node-geoms-1) 

> The path from dem60 to dem65 is not visible.

This is due to the poor sizing of the image made above in a regular plot it should be alright


The code that creates this plot is here, so feel free to make a PR if you feel there's room for more improvements ☺️ 

https://github.com/easystats/see/blob/7f493766bb55a7638997b9e825c2b74d535da31c/R/plot.parameters_sem.R#L93-L150
